export const UserActionTypes = {
    /**
     * Login Action types
     */
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
  
    /**
     * Signup Action types
     */
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_ERROR: "SIGN_UP_ERROR",
  
    /**
     * Search User Action types
     */
    USERS_SERACH_START: "USERS_SERACH_START",
    USERS_SERACH_SUCCESS: "USERS_SERACH_SUCCESS",
    USERS_SERACH_ERROR: "USERS_SERACH_ERROR",

    FETCH_USER_START:"FETCH_USER_START",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
    FETCH_USER_ERROR:"FETCH_USER_ERROR",

    UPDATE_USER_START:"UPDATE_USER_START",
    UPDATE_USER_SUCCESS:"UPDATE_USER_SUCCESS",
    UPDATE_USER_ERROR:"UPDATE_USER_ERROR",

    LOG_OUT: "LOG_OUT",
  };
  