export const AuctionActionTypes ={
    AUCTIONS_FETCH_SUCCESS:"AUCTIONS_FETCH_SUCCESS",
    AUCTIONS_FETCH_START:"AUCTIONS_FETCH_START",
    AUCTIONS_FETCH_ERROR:"AUCTIONS_FETCH_ERROR",
    
    AUCTION_FETCH_START:"AUCTION_FETCH_START",
    AUCTION_FETCH_SUCCESS:"AUCTION_FETCH_SUCCESS",
    AUCTION_FETCH_ERROR:"AUCTION_FETCH_ERROR",

    AUCTION_CREATE_START:"AUCTION_CREATE_START",
    AUCTION_CREATE_SUCCESS:"AUCTION_CREATE_SUCCESS",
    AUCTION_CREATE_ERROR:"AUCTION_CREATE_ERROR",
    CLEAR_AUCTION_CREATE_SUCCESS:"CLEAR_AUCTION_CREATE_SUCCESS",

    AUCTION_UPDATE_START:"AUCTION_UPDATE_START",
    AUCTION_UPDATE_SUCCESS:"AUCTION_UPDATE_SUCCESS",
    AUCTION_UPDATE_ERROR:"AUCTION_UPDATE_ERROR",

    AUCTION_DELETE_START:"AUCTION_DELETE_START",
    AUCTION_DELETE_SUCCESS:"AUCTION_DELETE_SUCCESS",
    AUCTION_DELETE_ERROR:"AUCTION_DELETE_ERROR",
   
}