export const ProductActionTypes ={
    PRODUCTS_FETCH_SUCCESS:"PRODUCTS_FETCH_SUCCESS",
    PRODUCTS_FETCH_START:"PRODUCTS_FETCH_START",
    PRODUCTS_FETCH_ERROR:"PRODUCTS_FETCH_ERROR",
    
    PRODUCT_FETCH_START:"PRODUCT_FETCH_START",
    PRODUCT_FETCH_SUCCESS:"PRODUCT_FETCH_SUCCESS",
    PRODUCT_FETCH_ERROR:"PRODUCT_FETCH_ERROR",

    PRODUCT_CREATE_START:"PRODUCT_CREATE_START",
    PRODUCT_CREATE_SUCCESS:"PRODUCT_CREATE_SUCCESS",
    PRODUCT_CREATE_ERROR:"PRODUCT_CREATE_ERROR",
    CLEAR_PRODUCT_CREATE_SUCCESS:"CLEAR_PRODUCT_CREATE_SUCCESS",

    PRODUCT_UPDATE_START:"PRODUCT_UPDATE_START",
    PRODUCT_UPDATE_SUCCESS:"PRODUCT_UPDATE_SUCCESS",
    PRODUCT_UPDATE_ERROR:"PRODUCT_UPDATE_ERROR",

    PRODUCT_DELETE_START:"PRODUCT_DELETE_START",
    PRODUCT_DELETE_SUCCESS:"PRODUCT_DELETE_SUCCESS",
    PRODUCT_DELETE_ERROR:"PRODUCT_DELETE_ERROR",
   
}